spring.application.name=moving-api

logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}


spring.datasource.url=jdbc:postgresql://172.31.130.254:5432/moving
spring.datasource.username=${env.DB_USERNAME:admin}
spring.datasource.password=${env.DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# 1. Show the SQL in the console
spring.jpa.show-sql=true

# 2. Make the SQL pretty and readable
spring.jpa.properties.hibernate.format_sql=true

# 3. Show the actual values (parameters) passed to the query
logging.level.org.hibernate.orm.jdbc.bind=trace